// OCaml dark theme for Monaco
export const caramlDarkTheme: any = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'keyword', foreground: 'c678dd', fontStyle: 'bold' },
    { token: 'type', foreground: '56b6c2' },
    { token: 'type.identifier', foreground: 'e5c07b' },
    { token: 'identifier', foreground: 'abb2bf' },
    { token: 'number', foreground: 'd19a66' },
    { token: 'number.float', foreground: 'd19a66' },
    { token: 'number.hex', foreground: 'd19a66' },
    { token: 'string', foreground: '98c379' },
    { token: 'string.char', foreground: '98c379' },
    { token: 'string.escape', foreground: '56b6c2' },
    { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
    { token: 'operator', foreground: '56b6c2' },
    { token: 'delimiter', foreground: 'abb2bf' },
    { token: '', foreground: 'abb2bf' },
  ],
  colors: {
    'editor.background': '#0a0e1a',
    'editor.foreground': '#abb2bf',
    'editor.lineHighlightBackground': '#1e293b40',
    'editor.selectionBackground': '#264f7840',
    'editor.inactiveSelectionBackground': '#264f7820',
    'editorCursor.foreground': '#06b6d4',
    'editorLineNumber.foreground': '#475569',
    'editorLineNumber.activeForeground': '#94a3b8',
    'editorIndentGuide.background': '#1e293b',
    'editorIndentGuide.activeBackground': '#334155',
    'editor.selectionHighlightBackground': '#264f7830',
    'editorBracketMatch.background': '#264f7830',
    'editorBracketMatch.border': '#06b6d480',
    'editorGutter.background': '#0a0e1a',
    'editorWidget.background': '#111827',
    'editorWidget.border': '#1e293b',
    'input.background': '#1e293b',
    'input.border': '#334155',
    'dropdown.background': '#111827',
    'list.hoverBackground': '#1e293b',
    'list.activeSelectionBackground': '#1e3a5f',
    'minimap.background': '#0a0e1a',
  },
};

// OCaml light theme for Monaco
export const caramlLightTheme: any = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'keyword', foreground: '7c3aed', fontStyle: 'bold' },
    { token: 'type', foreground: '0891b2' },
    { token: 'type.identifier', foreground: 'b45309' },
    { token: 'identifier', foreground: '334155' },
    { token: 'number', foreground: 'c2410c' },
    { token: 'number.float', foreground: 'c2410c' },
    { token: 'number.hex', foreground: 'c2410c' },
    { token: 'string', foreground: '16a34a' },
    { token: 'string.char', foreground: '16a34a' },
    { token: 'string.escape', foreground: '0891b2' },
    { token: 'comment', foreground: '94a3b8', fontStyle: 'italic' },
    { token: 'operator', foreground: '0891b2' },
    { token: 'delimiter', foreground: '475569' },
    { token: '', foreground: '334155' },
  ],
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#334155',
    'editor.lineHighlightBackground': '#f1f5f920',
    'editor.selectionBackground': '#bfdbfe60',
    'editor.inactiveSelectionBackground': '#bfdbfe30',
    'editorCursor.foreground': '#0891b2',
    'editorLineNumber.foreground': '#94a3b8',
    'editorLineNumber.activeForeground': '#475569',
    'editorIndentGuide.background': '#e2e8f0',
    'editorIndentGuide.activeBackground': '#cbd5e1',
    'editor.selectionHighlightBackground': '#bfdbfe40',
    'editorBracketMatch.background': '#bfdbfe40',
    'editorBracketMatch.border': '#0891b280',
    'editorGutter.background': '#ffffff',
    'editorWidget.background': '#f8fafc',
    'editorWidget.border': '#e2e8f0',
    'input.background': '#f1f5f9',
    'input.border': '#e2e8f0',
    'dropdown.background': '#ffffff',
    'list.hoverBackground': '#f1f5f9',
    'list.activeSelectionBackground': '#dbeafe',
    'minimap.background': '#ffffff',
  },
};
